---
name: Lint
on:
  - push

jobs:
  salt-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install python3-pip
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install salt-lint
        run: |
          sudo pip3 install salt-lint
      - name: Run salt-lint
        run: |
          salt-lint $(find . -name '*.sls')
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - name: Install rubocop
        run: |
          sudo gem install rubocop
      - name: Run rubocop
        run: |
          rubocop -d -P -S --enable-pending-cops
